<e>  ::=  (<e>+<e>) |
	 	  (<e>-<e>) |
		  (<e>*<e>) |
		  aq(<e>,<e>) |
		  x[<idx>] |
		  c[<idx>] # we allow limited number of constants: same as number of variables
<idx> ::= GE_RANGE:dataset_n_vars
